rails-task-manager/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # #get all the tasks
  # get "tasks", to: "tasks#index"

  # #get the form to create a new task
  # get "tasks/new", to: "tasks#new", as: :new_task
  # #post a new task
  # post "tasks", to: "tasks#create"

  # #get just one taks
  # get "tasks/:id", to: "tasks#show", as: :task

  # #get the form to edit an existing task
  # get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  # #update an existing task
  # patch "tasks/:id", to: "tasks#update"

  # #delete an existing task
  # delete "tasks/:id", to: "tasks#destroy"


  resources :tasks

  patch "tasks/:id/done", to: "tasks#mark_as_done", as: :done_task

end

rails-task-manager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-task-manager/app/models/task.rb
class Task < ApplicationRecord
end

rails-task-manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails-task-manager/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :mark_as_done]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def mark_as_done
    @task.done = true
    @task.save
    redirect_to task_path(@task)
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description)
  end

end

rails-task-manager/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-task-manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails-task-manager/app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

rails-task-manager/app/views/tasks/edit.html.erb
<%= render 'form' %>

rails-task-manager/app/views/tasks/index.html.erb
<h1>Tasks List</h1>

<% @tasks.each do |task| %>
  <h2><%= link_to task.title,task_path(task) %> <%= task.done == true ? "[X]" : "[ ]"%></h2>
  <%= link_to "Edit", edit_task_path(task) %>
  <%= link_to "Delete", task_path(task), method: :delete, data: { confirm: "Are you sure?" }%>
  <%= link_to "Mark as done", done_task_path(task), method: :patch%>
<% end %>

<p><%= link_to "New task", new_task_path%></p>

rails-task-manager/app/views/tasks/new.html.erb
<%= render 'form' %>

rails-task-manager/app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p>Description: <%= @task.description %></p>
<p>Task done: <%= @task.done == true ? "[X]" : "[ ]"%></p>
<p><%= link_to "Back to all tasks", tasks_path%></p>